services:
  app-web:
    build:
      dockerfile: Dockerfile 
      context: .
    ports:
      - 8000:8000
    env_file: ./.env
    develop:
      watch:
        - action: rebuild
          path: ./src
          target: /app
        - action: rebuild
          path: requirements.txt
          target: requirements.txt
        - action: rebuild
          path: ./.env